-- Script para eliminar todas las tablas del proyecto antes de
-- volver a correr 03_creacion_DB.sql desde cero.
-- CASCADE CONSTRAINTS elimina las llaves foraneas dependientes;
-- PURGE evita que las tablas queden en la papelera de reciclaje
-- de Oracle (libera el espacio de una vez).

DROP TABLE pago CASCADE CONSTRAINTS PURGE;
DROP TABLE detalle_venta CASCADE CONSTRAINTS PURGE;
DROP TABLE venta CASCADE CONSTRAINTS PURGE;
DROP TABLE producto CASCADE CONSTRAINTS PURGE;
DROP TABLE cliente CASCADE CONSTRAINTS PURGE;
DROP TABLE empleado CASCADE CONSTRAINTS PURGE;
DROP TABLE tienda CASCADE CONSTRAINTS PURGE;
DROP TABLE municipio CASCADE CONSTRAINTS PURGE;
DROP TABLE departamento CASCADE CONSTRAINTS PURGE;
DROP TABLE metodo_pago CASCADE CONSTRAINTS PURGE;
DROP TABLE estado_venta CASCADE CONSTRAINTS PURGE;
DROP TABLE marca CASCADE CONSTRAINTS PURGE;
DROP TABLE categoria CASCADE CONSTRAINTS PURGE;
DROP TABLE tipo_identificacion CASCADE CONSTRAINTS PURGE;
DROP TABLE cargo CASCADE CONSTRAINTS PURGE;
DROP TABLE tipo_tienda CASCADE CONSTRAINTS PURGE;
DROP TABLE pais CASCADE CONSTRAINTS PURGE;
